version: '3.3'
services:

  api:
    build: 
      context: ./api
    container_name: api
    restart: always
    working_dir: /go/src/github.com/KafkaService/api
    ports:
      - "3333:8080"
    command: ./main
    depends_on:
      - zookeeper
      - kafka

  # producer:
  #   build: 
  #     context: ./producer
  #   container_name: producer
  #   restart: always
  #   working_dir: /go/src/github.com/KafkaService/producer
  #   ports:
  #     - "3232:8080"
  #   command: ./main
  #   depends_on:
  #     - zookeeper
  #     - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zoo
    ports:
      - "2181:2181"
      
  kafka:
    image: ches/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=${HOSTNAME}
      - ZOOKEEPER_IP=zookeeper
    depends_on:
      - zookeeper